<?php
/*
	Question2Answer 1.7.0 (c) 2015, Gideon Greenspan
	http://www.question2answer.org/

	File: qa-include/qa-lang-question.php
	Version: 1.7.0
	Date: 2015-06-28 06:58:57 GMT
	Description: Language phrases for email notifications
	Language file updated from 1.6.x to 1.7.0 by http://www.klokkenluider.org
	Keep file as UTF-8 by http://www.klokkenluider.org ÓßÔÒõÕµþÞÚÛÙýÝ¯´±‗¾¶§÷¨·¹³²

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/
return array(
	'1_answer_title' => '1 Antwoord',
	'a_convert_to_c' => 'Wijzig dit antwoord in een opmerking',
	'a_convert_to_c_on' => 'Wijzig dit antwoord in een opmerking op:',
	'a_convert_warn' => 'Waarschuwing: Deze wijziging kan niet ongedaan gemaakt worden',
	'a_convert_warn_cs' => 'Waarschuwing: Deze wijziging kan niet ongedaan gemaakt worden en zal ook alle opmerkingen op dit antwoord verwijderen.',
	'a_notify_email' => 'Email me op dit adres als mijn antwoord geselecteerd wordt of er een opmerking komt:',
	'a_notify_label' => 'Email me als mijn antwoord geselecteerd wordt of er een opmerking komt',
	'a_notify_x_label' => 'Email me (^) als mijn antwoord geselecteerd wordt of er een opmerking komt',
	'a_waiting_your_approval' => "Dit antwoord wacht nog op je toestemming",
	'a_your_waiting_approval' => "Je antwoord wacht nog op toestemming",
	'add_answer_button' => 'Antwoord toevoegen',
	'add_comment_button' => 'Opmerking toevoegen',
	'add_q_favorites' => "Voeg deze vraag toe aan mijn favorieten",
	'anon_name_label' => "Je weer te geven naam (optioneel):",
	'answer_button' => 'antwoord',
	'answer_limit' => 'Teveel antwoorden ontvangen. Probeer nogmaals over een uur',
	'answer_must_be_approved' => "Je account moet goedgekeurd zijn voordat je een vraag kan beantwoorden.",
	'answer_must_confirm' => 'Aub. ^5e-mailadres bevestigen^6 om deze vraag te beantwoorden.',
	'answer_must_login' => 'Aub. ^1inloggen^2 or ^3registreren^4 om deze vraag te beantwoorden.',
	'answer_q_popup' => 'Beantwoord deze vraag',
	'approve_a_popup' => "Keur dit antwoord goed",
	'approve_button' => "toestaan",
	'approve_c_popup' => "Keur dit kommentaar goed",
	'approve_q_popup' => "Keur deze vraag goed",
	'ask_button' => 'Stel vraag',
	'ask_follow_from_a' => 'Je vraag wordt gerelateerd aan dit antwoord:',
	'ask_follow_title' => 'Stel een gerelateerde vraag',
	'ask_limit' => 'Teveel vragen gesteld. Probeer nogmaals over een uur',
	'ask_must_be_approved' => "Je account moet goedgekeurd zijn voordat je een vraag kan stellen.",
	'ask_must_confirm' => 'Aub. ^5e-mailadres bevestigen^6 om een vraag te stellen.',
	'ask_must_login' => 'Aub. ^1inloggen^2 or ^3registreren^4 om een vraag te stellen.',
	'ask_same_q' => 'Voordat je doorgaat, controleer of deze vraag niet al gesteld is:',
	'ask_title' => 'Stel een vraag',
	'c_notify_email' => 'Email me op dit adres als er een opmerking wordt toegevoegd:',
	'c_notify_label' => 'Email me als er een opmerking wordt toegevoegd',
	'c_notify_x_label' => 'Email me (^) als er een opmerking wordt toegevoegd',
	'c_waiting_your_approval' => "Deze opmerking wacht nog op je toestemming",
	'c_your_waiting_approval' => "Je opmerking wacht nog op toestemming",
	'category_ask_not_allowed' => "Je hebt geen permissie om vragen in deze categorie te stellen.",
	'category_js_note' => 'Activeer JavaScript in je browser om een categorie te kiezen',
	'category_required' => 'Kies een categorie',
	'claim_a_popup' => "Wijs dit antwoord toe aan je gebruikers account",
	'claim_button' => 'Ik schreef dit',
	'claim_c_popup' => "Wijs dit kommentaar toe aan je gebruikers account",
	'claim_q_popup' => "Wijs deze vraag toe aan je gebruikers account",
	'clear_flags_button' => 'markeringen opheffen',
	'clear_flags_popup' => 'Alle markeringen van alle gebruikers opheffen',
	'close_button' => "sluit",
	'close_duplicate' => "Dit is een dubbele of een andere vraag",
	'close_duplicate_error' => "De dubbele vraag kon niet gevonden worden - probeer alsjeblieft het nummer van een andere vraag URL, bijv. 123.",
	'close_form_button' => "Sluit vraag",
	'close_form_title' => "Sluit deze vraag",
	'close_original_note' => "Je kunt ook het vraagnummer van de URL intypen, bijv. 123.",
	'close_original_title' => "URL van de originele vraag:",
	'close_q_popup' => "Sluit deze vraag voor nieuwe antwoorden",
	'close_reason_title' => "Reden voor sluiting van deze vraag:",
	'closed_as_duplicate' => "Gesloten omdat deze vraag al gesteld is:",
	'closed_with_note' => "Gesloten met het bericht:",
	'comment_a_popup' => 'Opmerking op dit antwoord plaatsen',
	'comment_button' => 'opmerking',
	'comment_limit' => 'Teveel opmerkingen ontvangen. Probeer nogmaals over een uur',
	'comment_must_be_approved' => "Je account moet goedgekeurd zijn voordat je een opmerking kan plaatsen.",
	'comment_must_confirm' => 'Aub. ^5e-mailadres bevestigen^6 om een opmerking te plaatsen.',
	'comment_must_login' => 'Aub. ^1inloggen^2 or ^3registreren^4 om een opmerking te plaatsen.',
	'comment_on_a' => 'Op antwoord ',
	'comment_on_q' => 'Op vraag: ',
	'comment_q_popup' => 'Voeg opmerking toe op deze vraag',
	'delete_a_popup' => 'Dit antwoord permanent verwijderen',
	'delete_button' => 'verwijderen',
	'delete_c_popup' => 'Deze opmerking permantent verwijderen',
	'delete_q_popup' => 'Deze vraag permanent verwijderen',
	'duplicate_content' => 'Je vraag lijkt een duplicaat te zijn.',
	'edit_a_popup' => 'Bewerk dit antwoord',
	'edit_a_title' => 'Bewerk antwoord',
	'edit_button' => 'bewerk',
	'edit_c_popup' => 'Bewerk deze opmerking',
	'edit_c_title' => 'Bewerk opmerking',
	'edit_must_confirm' => 'Aub. ^5e-mailadres bevestigen^6 om dit te bewerken.',
	'edit_must_login' => 'Aub. ^1inloggen^2 or ^3registreren^4 om dit te bewerken.',
	'edit_q_popup' => 'Bewerk deze vraag',
	'edit_q_title' => 'Bewerk vraag',
	'example_tags' => 'Voorbeeld tags: ',
	'flag_a_popup' => 'Markeer dit antwoord als spam of ongepast',
	'flag_button' => 'markeer',
	'flag_c_popup' => 'Markeer deze opmerking als spam of ongepast',
	'flag_hide_button' => 'markeer en verberg',
	'flag_limit' => 'Teveel berichten gemarkeerd. Probeer opnieuw over een uur.',
	'flag_must_confirm' => 'Aub. ^5e-mailadres bevestigen^6 om een bericht te markeren.',
	'flag_must_login' => 'Aub. ^1inloggen^2 or ^3registreren^4 om bericht te markeren.',
	'flag_not_allowed' => 'Dit markeren is niet toegstaan',
	'flag_q_popup' => 'Markeer deze vraag als spam of ongepast',
	'follow_a_popup' => 'Stel een nieuwe vraag gerelateerd aan dit antwoord',
	'follow_button' => 'Stel een gerelateerde vraag',
	'follows_a' => 'gerelateerd aan een antwoord op:',
	'follows_q' => 'over de vraag:',
	'hide_a_popup' => 'Verberg dit antwoord',
	'hide_button' => 'verberg',
	'hide_c_popup' => 'Verberg deze opmerking',
	'hide_q_popup' => 'Verberg deze vraag',
	'matching_tags' => 'Overeenkomende tags: ',
	'max_tags_x' => 'Maximaal ^ tags zijn toegestaan',
	'min_tags_x' => 'Geef minimaal ^ tag(s) op',
	'notify_email_note' => 'Privacy: Je e-mailadres wordt uitsluitend gebruikt om deze notificaties te sturen.',
	'q_category_label' => 'Categorie:',
	'q_content_label' => 'Meer informatie over je vraag:',
	'q_hidden_author' => 'Deze vraag is verborgen door de auteur',
	'q_hidden_flagged' => 'Deze vraag is gemarkeerd en verborgen',
	'q_hidden_other' => 'Deze vraag is verborgen',
	'q_notify_email' => 'Email me op dit adres als mijn vraag beantwoord wordt of er een opmerking komt:',
	'q_notify_label' => 'Email me als mijn vraag beantwoord wordt of er een opmerking komt',
	'q_notify_x_label' => 'Email me (^) als mijn vraag beantwoord wordt of er een opmerking kom',
	'q_tags_comma_label' => 'Tags - gebruik komma (,) als a scheidingsteken:',
	'q_tags_label' => 'Tags gescheiden door een spatie (gebruik min-tekens om woorden combineren):',
	'q_title_label' => 'Je vraag in 1 zin:',
	'q_waiting_approval' => "Deze vraag wacht nog op je toestemming",
	'q_waiting_your_approval' => "Deze vraag wacht nog op je toestemming",
	'q_your_waiting_approval' => "Je vraag wacht nog op je toestemming",
	'recat_button' => "hercategoriseer",
	'recat_popup' => "Verander de categorie van deze vraag",
	'recat_q_title' => "Hercategoriseer vraag",
	'reject_a_popup' => "Verwijder dit antwoord",
	'reject_button' => "weiger",
	'reject_c_popup' => "Verwijder dit kommentaar",
	'reject_q_popup' => "Verwijder deze vraag",
	'remove_q_favorites' => "Verwijder deze vraag uit mijn favorieten",
	'reopen_button' => "heropen",
	'reopen_q_popup' => "Heropen deze vraag",
	'reply_button' => 'antwoord',
	'reply_c_popup' => 'Antwoord op deze opmerking',
	'reshow_a_popup' => "Laat dit antwoord opnieuw zien",
	'reshow_button' => 'opnieuw tonen',
	'reshow_c_popup' => "Laat dit kommentaar opnieuw zien",
	'reshow_q_popup' => "Laat deze vraag opnieuw zien",
	'retag_button' => "hertag",
	'retag_cat_popup' => "Verander van deze vraag de categorie of tags",
	'retag_popup' => "Verander van deze vraag de tags",
	'retag_q_title' => "Hertag vraag",
	'save_silent_label' => "Stil opslaan om te verbergen dat dit was bewerkt",
	'select_popup' => 'Klik om te selecteren als beste antwoord',
	'select_text' => 'Beste antwoord',
	'show_1_comment' => "Toon 1 opmerking",
	'show_1_previous_comment' => "Toon 1 vorige opmerking",
	'show_x_comments' => "Toon ^ opmerkingen",
	'show_x_previous_comments' => "Toon ^ vorige opmerkingen",
	'unflag_button' => 'demarkeren',
	'unflag_popup' => 'Verwijder de markering die je hebt gedaan',
	'unselect_popup' => 'Klik om selectie te verwijderen',
	'x_answers_title' => '^ Antwoorden',
	'your_answer_title' => 'Jouw antwoord',
	'your_comment_a' => 'Jouw opmerking op dit antwoord:',
	'your_comment_q' => 'Jouw opmerking op deze vraag:',
);
/*
	Omit PHP closing tag to help avoid accidental output
*/ 
